### ISSUE TITLE
RNN-SMT with pytorch

### ISSUE THREAD

**Issue by liperrino** [shihan9/RNN-SMT#1]
I am interest in your work but i am not good in Tensorflow and even in laguage translation, i am a novice. I would like to reproduce this repository in Pytorch but i do not know how to start. Please can you help me. I would like in particular know how to deal with out of words vocabulary( words that are tag with 'unk' token), because i have seen some scripts under the scripts directory that deal with it i am right. I would like please that you tell how they work and how to use them. Thanks in advance. Cheers

**Comment by zshihang** [comment]
try looking into the PyTorch tutorial https://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html.
